### ISSUE TITLE
Rolling TODO

### ISSUE THREAD

**Issue by brekk** [open-sorcerers/open-sorcerers#27]
Rolling TODO:

- [ ] make use of `emotion-theming`
- [ ] storybook is broken(?)
- [ ] re: https://github.com/open-sorcerers/open-sorcerers/issues/15 we should do that for `website` especially
- [ ] SEO - write a test to prove title / keywords / description
- [x] text truncated on mobile
- [ ] revised publishing approaches
- [ ] check colors in accessibility
- [ ] check links
- [x] EDIT - make sure all pages link to their edit page on github
- [x] Design a "coming soon" wrapper component which makes links invalid but obviously so
- [x] Password protect private / draft pages
- [x] cog is too big above MID_TABLET breakpoints, gets in the way of the titles
- [x] custom 404
- [x] post colophon to give time context to the series
- [x] link to the shoulders of giants -- add a references page

And more!

**Comment by brekk** [comment]
- Content on webkit
- coming soon
- password protected pages
added in https://github.com/open-sorcerers/open-sorcerers/pull/30

**Comment by brekk** [comment]
404 - https://github.com/open-sorcerers/open-sorcerers/pull/32

**Comment by brekk** [comment]
Closing this in favor of: https://github.com/open-sorcerers/open-sorcerers/issues/36
