### ISSUE TITLE
Rolling TODO - Jan. 27

### ISSUE THREAD

**Issue by brekk** [open-sorcerers/open-sorcerers#36]
Rolling TODO - flushing https://github.com/open-sorcerers/open-sorcerers/issues/27:

- [ ] make use of `emotion-theming`
- [ ] storybook is broken(?)
- [ ] re: https://github.com/open-sorcerers/open-sorcerers/issues/15 we should do that for `website` especially
- [ ] SEO - write a test to prove title / keywords / description
- [ ] revised publishing approaches
- [ ] check colors in accessibility
- [ ] check links

And more!

**Comment by brekk** [comment]
https://github.com/open-sorcerers/open-sorcerers/pull/37
- Date parsing wasn't fuxy, written dates were incorrect: 2020-12-31 vs. 2020-31-12
